print("Tip Calculator")
print()
TotalBill = float(input("How much was the bill?: "))
print()
Tip = int(input("What percentage do you want to tip?: "))
print()
TotalPeople = int(input("How many people were in your group?: "))
print()
TipAmount = TotalBill * (Tip/100)
TipAmount = round(TipAmount, 2)
print("Each of you owe $", TipAmount/TotalPeople + TotalBill/TotalPeople)